/**
 * Single-file HTML report renderer — pure function over {@link RenderInput}.
 *
 * Zero external dependencies: one document with embedded CSS and a few lines
 * of inline script (theme toggle + print expansion). Sections: KPI cards,
 * turn timeline, tool ranking, error-highlighted transcript, print-friendly.
 *
 * v1.0.0 extras: JSON syntax highlighting for tool arguments/results,
 * bilingual labels (`lang: 'en' | 'zh'`), native tooltips on charts, and an
 * error-jump anchor that links to the first failed tool result.
 *
 * @module dsh-session-export/render/html
 */
import type { ContentBlock } from '@deepseek-ai/dsh-llm'
import type { RenderInput } from '../types.ts'
import { asAssistant, asToolResult } from '../types.ts'
import { formatDuration } from '../stats.ts'
import { parseToolArguments, renderToolDiff } from './diff.ts'
import { truncate } from '../util/truncate.ts'

/** Report label language; English is the default. */
export type ReportLang = 'en' | 'zh'

export interface HtmlRenderOptions {
  readonly argCharLimit: number
  readonly resultCharLimit: number
  /** UI label language for the report (default `'en'`). */
  readonly lang?: ReportLang
}

export const defaultHtmlOptions: HtmlRenderOptions = {
  argCharLimit: 512,
  resultCharLimit: 2048,
}

function escapeHtml(text: string): string {
  return text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
}

function fmtTime(epochMs: number): string {
  return new Date(epochMs).toISOString().replace('T', ' ').replace(/\.\d+Z$/, 'Z')
}

function fmtTokens(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`
  return String(n)
}

function id8(id: string): string {
  return id.replace(/^session-/, '').slice(0, 8)
}

// ─── i18n ────────────────────────────────────────────────────────────────────

type LabelKey =
  | 'title' | 'messages' | 'toolCalls' | 'tokensIn' | 'tokensOut' | 'duration' | 'turns' | 'cost'
  | 'failedNote' | 'sparkline' | 'turnTimeline' | 'turn' | 'toolCallsSection' | 'transcript'
  | 'user' | 'assistant' | 'toolResult' | 'result' | 'reasoning' | 'toolFailed'
  | 'jumpError' | 'footer' | 'theme'
  | 'tipMessages' | 'tipToolCalls' | 'tipTokens' | 'tipDuration' | 'tipTurns' | 'tipCost'
  | 'tipTurn' | 'tipSpark' | 'tipTool'

const LABELS: Record<LabelKey, { readonly en: string; readonly zh: string }> = {
  title: { en: 'DSH session {id} — transcript', zh: 'DSH 会话 {id} — 转录报告' },
  messages: { en: 'Messages', zh: '消息' },
  toolCalls: { en: 'Tool calls', zh: '工具调用' },
  tokensIn: { en: 'Tokens in', zh: '输入 token' },
  tokensOut: { en: 'Tokens out', zh: '输出 token' },
  duration: { en: 'Duration', zh: '时长' },
  turns: { en: 'Turns', zh: '轮次' },
  cost: { en: 'Cost ≈', zh: '成本 ≈' },
  failedNote: { en: '{n} failed', zh: '{n} 次失败' },
  sparkline: { en: 'Output tokens per assistant message', zh: '每条助手消息的输出 token' },
  turnTimeline: { en: 'Turn timeline', zh: '轮次时间轴' },
  turn: { en: 'Turn {n}', zh: '第 {n} 轮' },
  toolCallsSection: { en: 'Tool calls', zh: '工具调用' },
  transcript: { en: 'Transcript', zh: '转录' },
  user: { en: 'User', zh: '用户' },
  assistant: { en: 'Assistant', zh: '助手' },
  toolResult: { en: 'Tool result', zh: '工具结果' },
  result: { en: 'result', zh: '结果' },
  reasoning: { en: 'Reasoning', zh: '推理' },
  toolFailed: { en: 'Tool failed:', zh: '工具失败：' },
  jumpError: { en: '⚠ {n} failed · jump to first', zh: '⚠ {n} 次失败 · 跳到第一个' },
  footer: {
    en: 'Generated by {g} at {t} — print to PDF for archival copies.',
    zh: '由 {g} 于 {t} 生成 — 打印为 PDF 可存档。',
  },
  theme: { en: '◐ theme', zh: '◐ 主题' },
  tipMessages: { en: 'Surface entries in log order', zh: '按日志顺序的表面条目数' },
  tipToolCalls: { en: 'Tool calls issued by the assistant', zh: '助手发出的工具调用' },
  tipTokens: { en: 'Sum of per-message usage records', zh: '按消息 usage 记录累加' },
  tipDuration: { en: 'First entry → last entry, wall clock', zh: '首条 → 末条的墙钟时长' },
  tipTurns: { en: 'User messages that started a turn', zh: '开启新一轮的用户消息数' },
  tipCost: { en: 'Estimate from the configured price table', zh: '按配置价格表估算' },
  tipTurn: { en: 'Turn {n} · {d}', zh: '第 {n} 轮 · {d}' },
  tipSpark: { en: '#{n} · {v} tokens', zh: '第 {n} 条 · {v} token' },
  tipTool: { en: '{n} calls', zh: '{n} 次调用' },
}

function t(key: LabelKey, lang: ReportLang): string {
  return LABELS[key][lang]
}

function tf(key: LabelKey, lang: ReportLang, vars: Readonly<Record<string, string | number>>): string {
  let out = LABELS[key][lang]
  for (const [name, value] of Object.entries(vars)) {
    out = out.replaceAll(`{${name}}`, String(value))
  }
  return out
}

// ─── JSON syntax highlighting (pattern-based, no dependency) ─────────────────

const JSON_TOKEN =
  /("(?:[^"\\]|\\.)*")(\s*:)?|-?\b\d+(?:\.\d+)?(?:[eE][+-]?\d+)?\b|\b(?:true|false)\b|\bnull\b/g

/** True when the full text parses as JSON (highlight gate; truncated views still render). */
function looksLikeJson(text: string): boolean {
  if (text.length === 0) return false
  try {
    JSON.parse(text)
    return true
  } catch {
    return false
  }
}

/** Wrap JSON tokens in colored spans; every segment is HTML-escaped. */
function highlightJson(text: string): string {
  let out = ''
  let last = 0
  for (const match of text.matchAll(JSON_TOKEN)) {
    const index = match.index ?? 0
    const token = match[0] ?? ''
    out += escapeHtml(text.slice(last, index))
    if (match[2] !== undefined) {
      out += `<span class="hl-key">${escapeHtml(match[1] ?? '')}</span><span class="hl-punc">${escapeHtml(match[2])}</span>`
    } else if (token.startsWith('"')) {
      out += `<span class="hl-str">${escapeHtml(token)}</span>`
    } else if (token === 'true' || token === 'false') {
      out += `<span class="hl-bool">${token}</span>`
    } else if (token === 'null') {
      out += '<span class="hl-null">null</span>'
    } else {
      out += `<span class="hl-num">${escapeHtml(token)}</span>`
    }
    last = index + token.length
  }
  out += escapeHtml(text.slice(last))
  return out
}

/** Truncated, escaped code block — JSON gets token colors, everything else stays plain. */
function renderCode(raw: string, limit: number): string {
  const shown = truncate(raw, limit)
  return looksLikeJson(raw) ? `<code class="json">${highlightJson(shown)}</code>` : `<code>${escapeHtml(shown)}</code>`
}

// ─── sections ────────────────────────────────────────────────────────────────

/** KPI card row: the numbers that describe the session. */
function renderKpiGrid(input: RenderInput, lang: ReportLang): string {
  const stats = input.stats
  const cards: Array<{ readonly label: LabelKey; readonly value: string; readonly note?: string; readonly tip: LabelKey }> = [
    { label: 'messages', value: String(input.totals.messages), tip: 'tipMessages' },
    {
      label: 'toolCalls',
      value: String(input.totals.toolCalls),
      note: stats !== undefined && stats.failedToolCalls > 0 ? tf('failedNote', lang, { n: stats.failedToolCalls }) : undefined,
      tip: 'tipToolCalls',
    },
    { label: 'tokensIn', value: fmtTokens(input.totals.inputTokens), tip: 'tipTokens' },
    { label: 'tokensOut', value: fmtTokens(input.totals.outputTokens), tip: 'tipTokens' },
    {
      label: 'duration',
      value: stats?.durationMs !== undefined && stats.durationMs !== null ? formatDuration(stats.durationMs) : '—',
      tip: 'tipDuration',
    },
    { label: 'turns', value: stats !== undefined ? String(stats.turns) : '—', tip: 'tipTurns' },
  ]
  const cost = stats?.cost
  if (cost !== undefined) {
    cards.push({
      label: 'cost',
      value: `${cost.currency}${cost.total >= 0.01 ? cost.total.toFixed(2) : cost.total.toFixed(4)}`,
      tip: 'tipCost',
    })
  }
  const spark = stats !== undefined ? renderSparklineSvg(stats.perAssistantTokens, lang) : ''
  return [
    '<section class="kpi-grid">',
    ...cards.map(
      ({ label, value, note, tip }) =>
        `<div class="kpi" title="${escapeHtml(t(tip, lang))}"><div class="kpi-label">${escapeHtml(t(label, lang))}</div><div class="kpi-value">${escapeHtml(value)}${
          note !== undefined ? ` <span class="kpi-note">${escapeHtml(note)}</span>` : ''
        }</div></div>`,
    ),
    spark !== ''
      ? `<div class="kpi kpi-wide" title="${escapeHtml(t('tipTokens', lang))}"><div class="kpi-label">${escapeHtml(t('sparkline', lang))}</div>${spark}</div>`
      : '',
    '</section>',
  ].join('\n')
}

/** Inline SVG bar sparkline: no JS, scales to card width, one tooltip per bar. */
function renderSparklineSvg(series: readonly number[], lang: ReportLang): string {
  if (series.length < 2) return ''
  const max = Math.max(...series)
  const W = 320
  const H = 40
  const gap = 2
  const barWidth = Math.max(1, (W - gap * (series.length - 1)) / series.length)
  const bars = series
    .map((value, index) => {
      const h = max === 0 ? 1 : Math.max(1, (value / max) * (H - 2))
      const x = index * (barWidth + gap)
      const y = H - h
      const tip = escapeHtml(tf('tipSpark', lang, { n: index + 1, v: value }))
      return `<rect x="${x.toFixed(1)}" y="${y.toFixed(1)}" width="${barWidth.toFixed(1)}" height="${h.toFixed(1)}" rx="1" title="${tip}"/>`
    })
    .join('')
  return `<svg class="sparkline" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img" aria-label="${escapeHtml(t('sparkline', lang))}">${bars}</svg>`
}

/** Turn timeline: one horizontal bar per user→next-user span, colored by duration share. */
function renderTimeline(input: RenderInput, lang: ReportLang): string {
  const entries = input.entries
  const starts = entries.filter((entry) => entry.message.role === 'user' && entry.message.source.kind !== 'tool')
  const durationMs = input.stats?.durationMs
  if (starts.length < 2 || durationMs === undefined || durationMs === null) return ''
  const totalMs = durationMs
  const rows = starts.map((start, index) => {
    const end = starts[index + 1]?.time ?? entries[entries.length - 1]?.time ?? start.time
    const ms = Math.max(0, end - start.time)
    const pct = totalMs === 0 ? 0 : (ms / totalMs) * 100
    const hue = 200 - Math.min(160, (pct / 100) * 160)
    const tip = escapeHtml(tf('tipTurn', lang, { n: index + 1, d: formatDuration(ms) }))
    return `<div class="tl-row"><span class="tl-label">${escapeHtml(tf('turn', lang, { n: index + 1 }))}</span><div class="tl-track"><div class="tl-bar" style="width:${pct.toFixed(1)}%;background:hsl(${hue.toFixed(0)},65%,50%)" title="${tip}"></div></div><span class="tl-dur">${escapeHtml(formatDuration(ms))}</span></div>`
  })
  return `<section class="card"><h2>${escapeHtml(t('turnTimeline', lang))}</h2>${rows.join('')}</section>`
}

/** Tool ranking bars. */
function renderToolRanking(input: RenderInput, lang: ReportLang): string {
  const breakdown = input.stats?.toolBreakdown ?? []
  if (breakdown.length === 0) return ''
  const max = breakdown[0]?.calls ?? 1
  const rows = breakdown.slice(0, 8).map((tool) => {
    const pct = (tool.calls / max) * 100
    const fail = tool.failures > 0 ? ` <span class="fail">${tool.failures}✗</span>` : ''
    const tip = escapeHtml(`${tool.name} · ${tf('tipTool', lang, { n: tool.calls })}`)
    return `<div class="tool-row"><span class="tool-name" title="${escapeHtml(tool.name)}">${escapeHtml(tool.name)}</span><div class="tool-track"><div class="tool-bar" style="width:${pct.toFixed(1)}%" title="${tip}"></div></div><span class="tool-count">${tool.calls}${fail}</span></div>`
  })
  return `<section class="card"><h2>${escapeHtml(t('toolCallsSection', lang))}</h2>${rows.join('')}</section>`
}

function renderBlocks(blocks: readonly ContentBlock[], options: HtmlRenderOptions): string[] {
  const lang = options.lang ?? 'en'
  const parts: string[] = []
  for (const block of blocks) {
    if (block.type === 'reasoning') {
      parts.push(
        `<details class="reasoning"><summary>${escapeHtml(t('reasoning', lang))}</summary><pre>${escapeHtml(block.text.trim())}</pre></details>`,
      )
    } else if (block.type === 'text') {
      parts.push(`<div class="msg-text">${escapeHtml(block.text.trim())}</div>`)
    } else if (block.type === 'tool-call') {
      const parsed = parseToolArguments(block.arguments)
      const diff = renderToolDiff(block.name, parsed)
      if (diff) {
        parts.push(
          `<details class="tool"><summary>🔧 ${escapeHtml(block.name)}</summary><pre class="diff">${escapeHtml(truncate(diff, options.resultCharLimit))}</pre></details>`,
        )
      } else {
        parts.push(
          `<details class="tool"><summary>🔧 ${escapeHtml(block.name)}</summary><pre>${renderCode(block.arguments, options.argCharLimit)}</pre></details>`,
        )
      }
    } else if ('content' in block) {
      const inner = block.content
        .map((inner2) => (inner2.type === 'text' ? inner2.text : `(${JSON.stringify(inner2.type)})`))
        .join('\n')
      parts.push(
        `<details class="tool-result"${block.isError === true ? ' open' : ''}><summary>🧾 ${escapeHtml(t('result', lang))}</summary><pre>${renderCode(inner, options.resultCharLimit)}</pre></details>`,
      )
    } else {
      parts.push(`<div class="unsupported">(${escapeHtml(JSON.stringify(block.type))})</div>`)
    }
  }
  return parts
}

function renderEntry(entry: RenderInput['entries'][number], options: HtmlRenderOptions, errorNo?: number): string {
  const lang = options.lang ?? 'en'
  const time = escapeHtml(fmtTime(entry.time))
  const message = entry.message
  const anchor = errorNo !== undefined ? ` id="error-${errorNo}"` : ''
  // Order matches buildEntries: assistant, then tool-result, then user —
  // tool-result messages carry role 'user' with a tool source.
  if (message.role === 'assistant') {
    const assistant = asAssistant(message)
    const provenance = assistant !== undefined ? `${assistant.source.provider} / ${assistant.source.model}` : ''
    const usage =
      entry.usage !== undefined
        ? ` · ${fmtTokens(entry.usage.inputTokens)} in / ${fmtTokens(entry.usage.outputTokens)} out`
        : ''
    const body = renderBlocks(message.content, options).join('\n')
    return `<article class="entry assistant"><header>🤖 ${escapeHtml(t('assistant', lang))} <span class="prov">${escapeHtml(provenance)}${escapeHtml(usage)}</span> <time>${time}</time></header>${body}</article>`
  }
  const toolResult = asToolResult(message)
  if (toolResult !== undefined) {
    const isError = entry.error !== undefined || toolResult.content.some((block) => block.isError === true)
    const errorLine =
      entry.error !== undefined
        ? `<div class="error-banner">${escapeHtml(t('toolFailed', lang))} <code>${escapeHtml(entry.error.name)}</code> (<code>${escapeHtml(entry.error.code)}</code>)</div>`
        : ''
    const body = renderBlocks(toolResult.content, options).join('\n')
    return `<article class="entry tool-result${isError ? ' error' : ''}"${anchor}><header>🧾 ${escapeHtml(t('toolResult', lang))} <code>${escapeHtml(id8(String(toolResult.source.callId)))}</code>${isError ? ' <span class="fail">⚠ ERROR</span>' : ''} <time>${time}</time></header>${errorLine}${body}</article>`
  }
  const body = renderBlocks(message.content, options).join('\n')
  return `<article class="entry user"><header>👤 ${escapeHtml(t('user', lang))} <time>${time}</time></header>${body}</article>`
}

function renderFilterNote(input: RenderInput): string {
  if (input.filterNote === undefined) return ''
  return `<div class="filter-note">⚠ ${escapeHtml(input.filterNote)}</div>`
}

const CSS = `
:root{color-scheme:light;--bg:#f6f7f9;--card:#fff;--ink:#1a1d21;--muted:#6b7280;--line:#e5e7eb;--accent:#2563eb;--fail:#dc2626;--bar:#93c5fd;--ok:#16a34a;--num:#b45309;--lit:#7c3aed}
@media (prefers-color-scheme:dark){:root:not([data-theme=light]){color-scheme:dark;--bg:#111317;--card:#1a1d23;--ink:#e5e7eb;--muted:#9ca3af;--line:#2a2e35;--accent:#60a5fa;--fail:#f87171;--bar:#3b82f6;--ok:#4ade80;--num:#fbbf24;--lit:#a78bfa}}
[data-theme=dark]{color-scheme:dark;--bg:#111317;--card:#1a1d23;--ink:#e5e7eb;--muted:#9ca3af;--line:#2a2e35;--accent:#60a5fa;--fail:#f87171;--bar:#3b82f6;--ok:#4ade80;--num:#fbbf24;--lit:#a78bfa}
*{box-sizing:border-box}
html{scroll-behavior:smooth}
body{margin:0 auto;max-width:960px;padding:24px 20px 64px;font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;background:var(--bg);color:var(--ink)}
h1{font-size:22px;margin:0 0 2px}
h2{font-size:15px;margin:0 0 12px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em}
.meta{color:var(--muted);font-size:13px;margin-bottom:18px}
.kpi-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:10px;margin:18px 0}
.kpi{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:12px 14px}
.kpi-label{font-size:11px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)}
.kpi-value{font-size:22px;font-weight:700;margin-top:2px}
.kpi-note{font-size:12px;color:var(--fail);font-weight:400}
.kpi-wide{grid-column:1/-1}
.sparkline{width:100%;height:40px;margin-top:8px;fill:var(--accent);opacity:.75}
.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin:14px 0}
.tl-row,.tool-row{display:flex;align-items:center;gap:10px;margin:6px 0}
.tl-label,.tool-name{width:110px;flex:none;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.tl-track,.tool-track{flex:1;height:12px;background:var(--line);border-radius:6px;overflow:hidden}
.tl-bar,.tool-bar{height:100%;border-radius:6px}
.tool-bar{background:var(--accent);opacity:.8}
.tl-dur,.tool-count{width:86px;flex:none;text-align:right;font-size:12px;color:var(--muted);font-variant-numeric:tabular-nums}
.fail{color:var(--fail);font-weight:700}
.jump-error{display:inline-block;margin:0 0 14px;color:var(--fail);text-decoration:none;border:1px solid var(--fail);border-radius:8px;padding:4px 10px;font-size:12px}
.jump-error:hover{background:rgba(220,38,38,.1)}
.entry{background:var(--card);border:1px solid var(--line);border-left:3px solid var(--line);border-radius:8px;padding:10px 14px;margin:10px 0}
.entry.user{border-left-color:#10b981}
.entry.assistant{border-left-color:var(--accent)}
.entry.tool-result{border-left-color:var(--bar)}
.entry.error{border-left-color:var(--fail);border-color:var(--fail)}
.entry.error:target{box-shadow:0 0 0 3px rgba(220,38,38,.3)}
.entry header{font-size:12px;color:var(--muted);margin-bottom:6px;display:flex;gap:8px;align-items:baseline;flex-wrap:wrap}
.entry time{margin-left:auto;font-variant-numeric:tabular-nums}
.prov{font-style:italic}
.msg-text{white-space:pre-wrap}
pre{background:rgba(127,127,127,.08);border-radius:8px;padding:10px 12px;overflow-x:auto;font-size:12.5px;line-height:1.5}
pre.diff{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
.hl-key{color:var(--accent);font-weight:600}
.hl-str{color:var(--ok)}
.hl-num{color:var(--num)}
.hl-bool,.hl-null{color:var(--lit)}
.hl-punc{color:var(--muted)}
details{margin:6px 0}
summary{cursor:pointer;font-size:13px;color:var(--muted)}
details[open] summary{color:var(--ink)}
.error-banner{background:rgba(220,38,38,.1);border:1px solid var(--fail);color:var(--fail);border-radius:8px;padding:8px 12px;margin:6px 0;font-size:13px}
.filter-note{background:rgba(217,119,6,.12);border:1px solid #d97706;color:#b45309;border-radius:8px;padding:8px 12px;margin:12px 0;font-size:13px}
footer{margin-top:28px;color:var(--muted);font-size:12px}
.theme-toggle{position:fixed;top:14px;right:16px;z-index:9;background:var(--card);color:var(--ink);border:1px solid var(--line);border-radius:8px;padding:5px 10px;cursor:pointer;font-size:12px}
[data-theme=light]{color-scheme:light}
[data-theme=dark]{color-scheme:dark}
@media print{.theme-toggle,.jump-error{display:none}body{background:#fff;color:#000;max-width:100%}.entry,.card,.kpi{break-inside:avoid;border-color:#bbb}pre{background:#f3f4f6}}
`

/** Render the complete single-file HTML report. */
export function renderHtml(input: RenderInput, options?: Partial<HtmlRenderOptions>): string {
  const opts = { ...defaultHtmlOptions, ...options }
  const lang = opts.lang ?? 'en'
  const h = input.header
  let errorCount = 0
  const entries = input.entries
    .map((entry) => {
      const isError =
        entry.error !== undefined ||
        (asToolResult(entry.message)?.content.some((block) => block.isError === true) ?? false)
      return renderEntry(entry, opts, isError ? ++errorCount : undefined)
    })
    .join('\n')
  const jump =
    errorCount > 0
      ? `<a class="jump-error" href="#error-1">${escapeHtml(tf('jumpError', lang, { n: errorCount }))}</a>`
      : ''
  const title = tf('title', lang, { id: id8(h.id) })
  return `<!doctype html>
<html lang="${lang === 'zh' ? 'zh-CN' : 'en'}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>${CSS}</style>
</head>
<body>
<button class="theme-toggle" type="button" aria-label="${escapeHtml(t('theme', lang))}">${escapeHtml(t('theme', lang))}</button>
<h1>${escapeHtml(title)}</h1>
<div class="meta">${escapeHtml(h.cwd ?? '')} · ${escapeHtml(h.createdAt ? fmtTime(h.createdAt) : '?')}${h.agentPreset !== undefined ? ` · ${escapeHtml(h.agentPreset)}` : ''}</div>
${renderFilterNote(input)}
${renderKpiGrid(input, lang)}
${jump}
${renderTimeline(input, lang)}
${renderToolRanking(input, lang)}
<section class="card"><h2>${escapeHtml(t('transcript', lang))}</h2>
${entries}
</section>
<footer>${escapeHtml(tf('footer', lang, { g: input.generator, t: fmtTime(input.generatedAt) }))}</footer>
<script>
(function(){
  var b=document.querySelector('.theme-toggle');
  var saved=null;try{saved=localStorage.getItem('dsh-theme')}catch(e){}
  if(saved){document.documentElement.dataset.theme=saved}
  b.addEventListener('click',function(){
    var cur=document.documentElement.dataset.theme||(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
    var next=cur==='dark'?'light':'dark';
    document.documentElement.dataset.theme=next;
    try{localStorage.setItem('dsh-theme',next)}catch(e){}
  });
  window.addEventListener('beforeprint',function(){
    var d=document.querySelectorAll('details');for(var i=0;i<d.length;i++){d[i].open=true}
  });
})();
</script>
</body>
</html>
`
}
